org.gradle.jvmargs=-Xmx5120M -Dfile.encoding=UTF-8
kotlin.compiler.execution.strategy=in-process
org.gradle.daemon=true
org.gradle.parallel=true
android.useAndroidX=true
android.enableR8.fullMode=true
kotlin.code.style=official

org.gradle.caching=true
org.gradle.configuration-cache=true
android.enableJetifier=false
android.nonTransitiveRClass=true